name: publish yuna to npm
on:
  released:
    types: [released]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    - name: checking out branch
      uses: actions/checkout@v2
    - name: stup node
      uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: https://registry.npmjs.org/
    - name: npm publish
      run: |
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_KEY}}
